--- # Groups
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cloud_and_infrastructure
  description: The infra business unit
spec:
  type: business-unit
  profile:
    displayName: Infrastructure
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: ops
  children: [backstage, other]
  #members: [jdoe]
--- # Components

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-catalog
  description: test
  tags:
    - servicecatalog
spec:
  type: service
  lifecycle: production
  owner: Cloud_and_Infrastructure
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloud-strategy-service
  description: test
  tags:
    - servicecatalog
spec:
  type: service
  lifecycle: production
  owner: Cloud_and_Infrastructure
  subcomponentOf: service-catalog
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloud-platform-service
  description: test
  tags:
    - servicecatalog
spec:
  type: service
  lifecycle: production
  owner: Cloud_and_Infrastructure
  subcomponentOf: service-catalog
  dependsOn: ["component:cloud-adoption-assessment"]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cloud-adoption-assessment
  description: test
  tags:
    - servicecatalog
spec:
  type: service
  lifecycle: production
  owner: Cloud_and_Infrastructure
  subcomponentOf: service-catalog
---
